-- ACCOUNT indexes
CREATE INDEX IF NOT EXISTS IDX_ACCOUNT_NAME ON core.ACCOUNT (NAME);
CREATE INDEX IF NOT EXISTS IDX_ACCOUNT_MAIL ON core.ACCOUNT (MAIL);

-- PERSONA indexes
CREATE INDEX IF NOT EXISTS IDX_PERSONA_ACCOUNT_ID ON core.PERSONA (ACCOUNT_ID);
CREATE INDEX IF NOT EXISTS IDX_PERSONA_PERS ON core.PERSONA (PERS);

-- PERSONA_CONNECTION indexes
CREATE INDEX IF NOT EXISTS IDX_PERSONA_CONNECTION_PERSONA_ID ON core.PERSONA_CONNECTION (PERSONA_ID);
CREATE INDEX IF NOT EXISTS IDX_PERSONA_CONNECTION_ADDRESS ON core.PERSONA_CONNECTION (ADDRESS);
CREATE INDEX IF NOT EXISTS IDX_PERSONA_CONNECTION_VERS ON core.PERSONA_CONNECTION (VERS);
CREATE INDEX IF NOT EXISTS IDX_PERSONA_CONNECTION_SLUS ON core.PERSONA_CONNECTION (SLUS);
CREATE INDEX IF NOT EXISTS IDX_PERSONA_CONNECTION_START_TIME ON core.PERSONA_CONNECTION (START_TIME);
CREATE INDEX IF NOT EXISTS IDX_PERSONA_CONNECTION_END_TIME ON core.PERSONA_CONNECTION (END_TIME);

-- GAME indexes
CREATE INDEX IF NOT EXISTS IDX_GAME_VERS ON core.GAME (VERS);
CREATE INDEX IF NOT EXISTS IDX_GAME_SLUS ON core.GAME (SLUS);
CREATE INDEX IF NOT EXISTS IDX_GAME_NAME ON core.GAME (NAME);
CREATE INDEX IF NOT EXISTS IDX_GAME_START_TIME ON core.GAME (START_TIME);
CREATE INDEX IF NOT EXISTS IDX_GAME_END_TIME ON core.GAME (END_TIME);

-- GAME_CONNECTION indexes
CREATE INDEX IF NOT EXISTS IDX_GAME_CONNECTION_GAME_ID ON core.GAME_CONNECTION (GAME_ID);
CREATE INDEX IF NOT EXISTS IDX_GAME_CONNECTION_PERSONA_CONNECTION_ID ON core.GAME_CONNECTION (PERSONA_CONNECTION_ID);
CREATE INDEX IF NOT EXISTS IDX_GAME_CONNECTION_START_TIME ON core.GAME_CONNECTION (START_TIME);
CREATE INDEX IF NOT EXISTS IDX_GAME_CONNECTION_END_TIME ON core.GAME_CONNECTION (END_TIME);

-- NFS_GAME_REPORT indexes
CREATE INDEX IF NOT EXISTS IDX_NFS_GAME_REPORT_VENUE ON stats.NFS_GAME_REPORT (VENUE);
CREATE INDEX IF NOT EXISTS IDX_NFS_GAME_REPORT_GTYP ON stats.NFS_GAME_REPORT (GTYP);
CREATE INDEX IF NOT EXISTS IDX_NFS_GAME_REPORT_DIR ON stats.NFS_GAME_REPORT (DIR);
CREATE INDEX IF NOT EXISTS IDX_NFS_GAME_REPORT_TIME ON stats.NFS_GAME_REPORT (TIME);
CREATE INDEX IF NOT EXISTS IDX_NFS_GAME_REPORT_POS ON stats.NFS_GAME_REPORT (POS);
CREATE INDEX IF NOT EXISTS IDX_NFS_GAME_REPORT_CAR ON stats.NFS_GAME_REPORT (CAR);
CREATE INDEX IF NOT EXISTS IDX_NFS_GAME_REPORT_RACETIME ON stats.NFS_GAME_REPORT (RACETIME);
CREATE INDEX IF NOT EXISTS IDX_NFS_GAME_REPORT_LAPSCOMP ON stats.NFS_GAME_REPORT (LAPSCOMP);
CREATE INDEX IF NOT EXISTS IDX_NFS_GAME_REPORT_LAP ON stats.NFS_GAME_REPORT (LAP);
CREATE INDEX IF NOT EXISTS IDX_NFS_GAME_REPORT_RNK ON stats.NFS_GAME_REPORT (RNK);

-- NFS_PERSONA_STATS indexes
CREATE INDEX IF NOT EXISTS IDX_NFS_PERSONA_STATS_VERS ON stats.NFS_PERSONA_STATS (VERS);
CREATE INDEX IF NOT EXISTS IDX_NFS_PERSONA_STATS_WINS ON stats.NFS_PERSONA_STATS (WINS);
CREATE INDEX IF NOT EXISTS IDX_NFS_PERSONA_STATS_LOSSES ON stats.NFS_PERSONA_STATS (LOSSES);
CREATE INDEX IF NOT EXISTS IDX_NFS_PERSONA_STATS_TIME ON stats.NFS_PERSONA_STATS (TIME);
CREATE INDEX IF NOT EXISTS IDX_NFS_PERSONA_STATS_RACETIME ON stats.NFS_PERSONA_STATS (RACETIME);
CREATE INDEX IF NOT EXISTS IDX_NFS_PERSONA_STATS_LAPSCOMP ON stats.NFS_PERSONA_STATS (LAPSCOMP);

-- MOHH_PERSONA_STATS indexes
CREATE INDEX IF NOT EXISTS IDX_MOHH_PERSONA_STATS_VERS ON stats.MOHH_PERSONA_STATS (VERS);
CREATE INDEX IF NOT EXISTS IDX_MOHH_PERSONA_STATS_KILL ON stats.MOHH_PERSONA_STATS (KILL);
CREATE INDEX IF NOT EXISTS IDX_MOHH_PERSONA_STATS_DEATH ON stats.MOHH_PERSONA_STATS (DEATH);
CREATE INDEX IF NOT EXISTS IDX_MOHH_PERSONA_STATS_SHOT ON stats.MOHH_PERSONA_STATS (SHOT);
CREATE INDEX IF NOT EXISTS IDX_MOHH_PERSONA_STATS_HIT ON stats.MOHH_PERSONA_STATS (HIT);
CREATE INDEX IF NOT EXISTS IDX_MOHH_PERSONA_STATS_HEAD ON stats.MOHH_PERSONA_STATS (HEAD);
CREATE INDEX IF NOT EXISTS IDX_MOHH_PERSONA_STATS_WIN ON stats.MOHH_PERSONA_STATS (WIN);
CREATE INDEX IF NOT EXISTS IDX_MOHH_PERSONA_STATS_LOSS ON stats.MOHH_PERSONA_STATS (LOSS);
CREATE INDEX IF NOT EXISTS IDX_MOHH_PERSONA_STATS_AXIS ON stats.MOHH_PERSONA_STATS (AXIS);
CREATE INDEX IF NOT EXISTS IDX_MOHH_PERSONA_STATS_ALLIES ON stats.MOHH_PERSONA_STATS (ALLIES);
CREATE INDEX IF NOT EXISTS IDX_MOHH_PERSONA_STATS_PLAYTIME ON stats.MOHH_PERSONA_STATS (PLAYTIME);

-- NHL_PERSONA_STATS indexes
CREATE INDEX IF NOT EXISTS IDX_NHL_PERSONA_STATS_VERS ON stats.NHL_PERSONA_STATS (VERS);
CREATE INDEX IF NOT EXISTS IDX_NHL_PERSONA_STATS_POINTS ON stats.NHL_PERSONA_STATS (POINTS);
CREATE INDEX IF NOT EXISTS IDX_NHL_PERSONA_STATS_WINS ON stats.NHL_PERSONA_STATS (WINS);
CREATE INDEX IF NOT EXISTS IDX_NHL_PERSONA_STATS_OT_WINS ON stats.NHL_PERSONA_STATS (OT_WINS);
CREATE INDEX IF NOT EXISTS IDX_NHL_PERSONA_STATS_LOSSES ON stats.NHL_PERSONA_STATS (LOSSES);
CREATE INDEX IF NOT EXISTS IDX_NHL_PERSONA_STATS_OT_LOSSES ON stats.NHL_PERSONA_STATS (OT_LOSSES);
CREATE INDEX IF NOT EXISTS IDX_NHL_PERSONA_STATS_SCORE ON stats.NHL_PERSONA_STATS (SCORE);

-- BUDDY indexes
CREATE INDEX IF NOT EXISTS IDX_BUDDY_FROM_PERSONA_ID ON social.BUDDY (FROM_PERSONA_ID);
CREATE INDEX IF NOT EXISTS IDX_BUDDY_TO_PERSONA_ID ON social.BUDDY (TO_PERSONA_ID);
CREATE INDEX IF NOT EXISTS IDX_BUDDY_LIST ON social.BUDDY (LIST);
CREATE INDEX IF NOT EXISTS IDX_BUDDY_STATUS ON social.BUDDY (STATUS);

-- MESSAGE indexes
CREATE INDEX IF NOT EXISTS IDX_MESSAGE_FROM_PERSONA_ID ON social.MESSAGE (FROM_PERSONA_ID);
CREATE INDEX IF NOT EXISTS IDX_MESSAGE_TO_PERSONA_ID ON social.MESSAGE (TO_PERSONA_ID);
CREATE INDEX IF NOT EXISTS IDX_MESSAGE_BODY ON social.MESSAGE (BODY);
CREATE INDEX IF NOT EXISTS IDX_MESSAGE_ACK ON social.MESSAGE (ACK);
