CREATE TABLE IF NOT EXISTS stats.FIFA_GAME_REPORT (
    GAME_CONNECTION_ID bigint PRIMARY KEY NOT NULL,
    VENUE numeric NOT NULL DEFAULT 0,                   -- venue/stadium id
    TEAM numeric NOT NULL DEFAULT 0,                    -- team selected
    PK numeric NOT NULL DEFAULT 0,                      -- penalty kicks
    GLD numeric NOT NULL DEFAULT 0,                     -- Golden goal ?
    SHT numeric NOT NULL DEFAULT 0,                     -- shots
    PASM numeric NOT NULL DEFAULT 0,                    -- passes missed
    PASS numeric NOT NULL DEFAULT 0,                    -- passes completed
    COR numeric NOT NULL DEFAULT 0,                     -- corners
    OFF numeric NOT NULL DEFAULT 0,                     -- offsides
    POS numeric NOT NULL DEFAULT 0,                     -- possession percentage
    TCM numeric NOT NULL DEFAULT 0,                     -- tackles missed
    TCS numeric NOT NULL DEFAULT 0,                     -- tackles successful
    FLS numeric NOT NULL DEFAULT 0,                     -- fouls
    YLW numeric NOT NULL DEFAULT 0,                     -- yellow cards
    RED numeric NOT NULL DEFAULT 0,                     -- red cards
    TIME numeric NOT NULL DEFAULT 0,                    -- ingame time
    TYPE numeric NOT NULL DEFAULT 0,                    -- game type
    SKIL numeric NOT NULL DEFAULT 0,                    -- skill level
    PLEN numeric NOT NULL DEFAULT 0,                    -- period length
    PNUM numeric NOT NULL DEFAULT 0,                    -- number of periods
    DISC numeric NOT NULL DEFAULT 0,                    -- disconnected (0/1)
    QUIT numeric NOT NULL DEFAULT 0,                    -- quit game (0/1)
    CHEAT numeric NOT NULL DEFAULT 0,                   -- cheated (0/1)
    DTIME numeric NOT NULL DEFAULT 0,                   -- ?
    SCORE numeric NOT NULL DEFAULT 0,                   -- final score
    WEIGHT numeric NOT NULL DEFAULT 0,                  -- ?
    DSCORE numeric NOT NULL DEFAULT 0,                  -- ?
    HOME numeric NOT NULL DEFAULT 0,                    -- home or away (0/1)
    RNK numeric NOT NULL DEFAULT 0,                     -- ranked or not
    CONSTRAINT FK_FIFA_GAME_REPORT_GAME_CONNECTION_ID FOREIGN KEY (GAME_CONNECTION_ID) REFERENCES core.GAME_CONNECTION(ID)
);

CREATE TABLE IF NOT EXISTS stats.FIFA_PERSONA_STATS (
    ID bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    PERSONA_ID bigint NOT NULL,
    VERS varchar(32) NOT NULL,
    SLUS varchar(10) NOT NULL,
    WINS numeric NOT NULL DEFAULT 0,                    -- total wins
    LOSSES numeric NOT NULL DEFAULT 0,                  -- total losses
    DRAW numeric NOT NULL DEFAULT 0,                    -- total draws
    SCORE numeric NOT NULL DEFAULT 0,                   -- total goals scored
    SCORE_AGAINST numeric NOT NULL DEFAULT 0,           -- total goals conceded
    SHT numeric NOT NULL DEFAULT 0,                     -- total shots
    PASM numeric NOT NULL DEFAULT 0,                    -- total passes missed
    PASS numeric NOT NULL DEFAULT 0,                    -- total passes completed
    COR numeric NOT NULL DEFAULT 0,                     -- total corners
    OFF numeric NOT NULL DEFAULT 0,                     -- total offsides
    POS numeric NOT NULL DEFAULT 0,                     -- total possession
    TCM numeric NOT NULL DEFAULT 0,                     -- total tackles missed
    TCS numeric NOT NULL DEFAULT 0,                     -- total tackles successful
    FLS numeric NOT NULL DEFAULT 0,                     -- total fouls
    YLW numeric NOT NULL DEFAULT 0,                     -- total yellow cards
    RED numeric NOT NULL DEFAULT 0,                     -- total red cards
    TIME numeric NOT NULL DEFAULT 0,                    -- total ingame time
    SKIL numeric NOT NULL DEFAULT 0,                    -- total skill
    DISC numeric NOT NULL DEFAULT 0,                    -- total disconnections
    QUIT numeric NOT NULL DEFAULT 0,                    -- total quits
    CHEAT numeric NOT NULL DEFAULT 0,                   -- total cheats
    WEIGHT numeric NOT NULL DEFAULT 0,                  -- total weight
    HOME numeric NOT NULL DEFAULT 0,                    -- total home games
    AWAY numeric NOT NULL DEFAULT 0,                    -- total away games
    CONSTRAINT FK_FIFA_PERSONA_STATS_PERSONA_ID FOREIGN KEY (PERSONA_ID) REFERENCES core.PERSONA(ID),
    CONSTRAINT UK_FIFA_PERSONA_STATS_PERSONA_VERS UNIQUE (PERSONA_ID, VERS)
);

-- FIFA_GAME_REPORT indexes
CREATE INDEX IF NOT EXISTS IDX_FIFA_GAME_REPORT_VENUE ON stats.FIFA_GAME_REPORT (VENUE);
CREATE INDEX IF NOT EXISTS IDX_FIFA_GAME_REPORT_TEAM ON stats.FIFA_GAME_REPORT (TEAM);
CREATE INDEX IF NOT EXISTS IDX_FIFA_GAME_REPORT_TIME ON stats.FIFA_GAME_REPORT (TIME);
CREATE INDEX IF NOT EXISTS IDX_FIFA_GAME_REPORT_SCORE ON stats.FIFA_GAME_REPORT (SCORE);
CREATE INDEX IF NOT EXISTS IDX_FIFA_GAME_REPORT_RNK ON stats.FIFA_GAME_REPORT (RNK);

-- FIFA_PERSONA_STATS indexes
CREATE INDEX IF NOT EXISTS IDX_FIFA_PERSONA_STATS_VERS ON stats.FIFA_PERSONA_STATS (VERS);
CREATE INDEX IF NOT EXISTS IDX_FIFA_PERSONA_STATS_WINS ON stats.FIFA_PERSONA_STATS (WINS);
CREATE INDEX IF NOT EXISTS IDX_FIFA_PERSONA_STATS_LOSSES ON stats.FIFA_PERSONA_STATS (LOSSES);
CREATE INDEX IF NOT EXISTS IDX_FIFA_PERSONA_STATS_DRAW ON stats.FIFA_PERSONA_STATS (DRAW);
CREATE INDEX IF NOT EXISTS IDX_FIFA_PERSONA_STATS_SCORE ON stats.FIFA_PERSONA_STATS (SCORE);
CREATE INDEX IF NOT EXISTS IDX_FIFA_PERSONA_STATS_SCORE_AGAINST ON stats.FIFA_PERSONA_STATS (SCORE_AGAINST);
CREATE INDEX IF NOT EXISTS IDX_FIFA_PERSONA_STATS_TIME ON stats.FIFA_PERSONA_STATS (TIME);
