server:
  port: ${SERVER_PORT:8080} # Local port

http:
  port: ${HTTP_PORT:80} # Tunnel port, exposed to the outside world
  dns_name: ${DNS_NAME:http://localhost}

ssl:
  protocols: 'SSLv3,TLSv1.2'
  cipher-suites: 'SSL_RSA_WITH_RC4_128_MD5,SSL_RSA_WITH_RC4_128_SHA'
  certificate:
    cipher-algorithm: 'MD5WITHRSA'
  debug:
    enabled: ${SSL_DEBUG_ENABLED:false}
tcp:
  # Must be machine IP if hosting for other machines. Must be WSL IP if using docker through WSL (local only)
  host: ${TCP_HOST_IP:127.0.0.1}
  buddy-port: ${TCP_BUDDY_PORT:5000}
  debug:
    enabled: ${TCP_DEBUG_ENABLED:false}
    exclusions: ${TCP_DEBUG_EXCLUSIONS:~png,+snp}
ssc2:
  key: 51ba8aee64ddfacae5baefa6bf61e009

spring:
  datasource:
    url: ${DB_URL}
    port: ${DB_PORT:5432}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:test@example.com}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  jpa:
#    hibernate:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

game:
  servers:
    - vers: 'BUDDY'
      aries: false
      ssl:
        enabled: false
      regions:
        - name: 'GLOBAL'
          port: 5000 # Arbitrary buddy port, set anything you want
    - vers: 'PSP/NFS06'
      sdk: '3.7.2.0'
      ssl:
        enabled: false # PSP/NFS06 SSL is bypassed as it uses SSLv2
        domain: 'pspnfs06.ea.com'
      regions:
        - name: 'GLOBAL'
          port: 30980 # default is 30990 for EU, but as it's duplicating PSP/NFS09 then it's patched to 30980 to match US version
          slus:
            - 'ULES00196'
            - 'ULUS10036'
    - vers: 'PSP/NFS07'
      sdk: '4.3.2'
      ssl:
        domain: 'pspnfs07.ea.com'
      regions:
        - name: 'EU'
          port: 10980
          slus:
            - 'ULES00577'
        - name: 'US'
          port: 10990
          slus:
            - 'ULUS10114'
    - vers: 'PSP/NFS08'
      sdk: '4.3.2'
      ssl:
        domain: 'pspnfs08.ea.com'
      regions:
        - name: 'EU'
          port: 20980
          slus:
            - 'SLUS-80296'
        - name: 'US'
          port: 20990
          slus:
            - 'SLUS-80296'
    - vers: 'PSP/NFS09'
      sdk: '4.3.2'
      ssl:
        domain: 'pspnfs09.ea.com'
      regions:
        - name: 'GLOBAL'
          port: 30990
          slus:
            - 'ULES01145'
            - 'ULUS10376'
    - vers: 'PSP/FIFA07'
      sdk: '4.3.2'
      ssl:
        domain: 'pspfifa07.ea.com'
      regions:
        - name: 'EU'
          port: 10490
          slus:
            - 'ULUS-10029' # Actual SLUS used by the game (PSP/FIFA06)
        - name: 'US'
          port: 10480
          slus:
            - 'ULUS-10029' # Actual SLUS used by the game (PSP/FIFA06)
    - vers: 'PSP/FIFA08'
      sdk: '5.5.0.0'
      ssl:
        domain: 'pspfifa08.ea.com'
      regions:
        - name: 'GLOBAL'
          port: 20490
          slus:
            - 'ULUS-10293'
    - vers: 'PSP/FIFA09'
      sdk: '6.3.1.0'
      ssl:
        domain: 'pspfifa09.ea.com'
      regions:
        - name: 'GLOBAL'
          port: 30490
          slus:
            - 'ULUX-80340'
    - vers: 'PSP/FIFA10'
      sdk: '7.5.3.0'
      ssl:
        domain: 'pspfifa10.ea.com'
      regions:
        - name: 'GLOBAL'
          port: 25490
          slus:
            - 'ULUS-10464'
    - vers: 'PSP/NCAA07'
      sdk: '4.2.2.0'
      ssl:
        domain: 'pspncaa07.ea.com'
      regions:
        - name: 'US-1'
          port: 10580
          slus:
            - 'ULUS10116'
        - name: 'US-2'
          port: 10590
          slus:
            - 'ULUS10116'
    - vers: 'PSP/MADDEN07'
      sdk: '4.3.2.0'
      ssl:
        domain: 'pspmadden07.ea.com'
      regions:
        - name: 'US'
          port: 10090
          slus:
            - 'SLUS-ULUS10117'
    - vers: 'PSP/MADDEN-2008'
      sdk: '5.3.2.1'
      ssl:
        domain: 'pspmadden08.ea.com'
      regions:
        - name: 'EU'
          port: 20080
          slus:
            - 'SLUS-ULES00867'
        - name: 'US'
          port: 20090
          slus:
            - 'SLUS-ULUS10275'
    - vers: 'PSP/MADDEN-2009'
      sdk: '5.6.5.7'
      ssl:
        domain: 'pspmadden09.ea.com'
      regions:
        - name: 'EU'
          port: 30080
          slus:
            - 'SLUS-ULES01093'
        - name: 'US'
          port: 30090
          slus:
            - 'SLUS-ULUS10352'
    - vers: 'PSP/MADDEN-2010'
      sdk: '7.3.1.1'
      ssl:
        domain: 'pspmadden10.ea.com'
      regions:
        - name: 'US'
          port: 25090
          slus:
            - 'SLUS-ULUS10441'
    - vers: 'PSP/NHL07'
      sdk: '4.3.2'
      ssl:
        domain: 'pspnhl07.ea.com'
      regions:
        - name: 'GLOBAL'
          port: 10390
          slus:
            - 'ULES00477'
            - 'ULUS10131'
    - vers: 'PSP/MOH07'
      sdk: '4.7.0'
      p2p: false
      dedicated:
        vers: 'PSP/MOHGPS071'
        slus: 'MOHA10000'
        port: 11190
      ssl:
        domain: 'pspmoh07.ea.com'
      regions:
        - name: "EU"
          port: 11180
          slus:
            - 'ULES00557'
            - 'ULES00558'
            - 'ULES00559'
            - 'ULES00560'
            - 'ULES00561'
            - 'ULES00562'
        - name: "US"
          port: 11190
          slus:
            - 'ULUS10141'

    - vers: 'PSP/MOH08'
      sdk: '5.6.2'
      p2p: false
      ssl:
        domain: 'pspmoh08.ea.com'
      regions:
        - name: 'EU'
          port: 21180
          slus:
            - 'ULES00955'
            - 'ULES00956'
            - 'ULES00988'
        - name: 'US'
          port: 21190
          slus:
            - 'ULUS10310'

    - vers: 'WII/MOH08'
      sdk: '5.6.2'
      p2p: false
      ssl:
        domain: 'wiimoh08.ea.com'
      regions:
        - name: 'EU'
          port: 21170
          slus:
            - 'RM2X'
            - 'RM2P'
        - name: 'US'
          port: 21120
          slus:
            - 'RM2E'

---

spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:ea-nation_db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master-populate.yaml