ALTER TABLE core.GAME ADD COLUMN IS_STARTED boolean NOT NULL DEFAULT false;
UPDATE core.GAME SET IS_STARTED = true WHERE IS_STARTED = false;

ALTER TABLE core.GAME ADD COLUMN ROOM_ID numeric NULL;

-- NHL Game Report table - stores individual game statistics
CREATE TABLE IF NOT EXISTS stats.NHL_GAME_REPORT (
    GAME_CONNECTION_ID bigint PRIMARY KEY NOT NULL,
    RNK numeric NOT NULL DEFAULT 0,                     -- ranked or not
    SCORE numeric NOT NULL DEFAULT 0,                   -- player score
    DSCORE numeric NOT NULL DEFAULT 0,                  -- ?
    HITS numeric NOT NULL DEFAULT 0,                    -- hits
    SHOTS numeric NOT NULL DEFAULT 0,                   -- shots to net
    PENMIN numeric NOT NULL DEFAULT 0,                  -- penalty minutes
    PPG numeric NOT NULL DEFAULT 0,                     -- power play goals
    PPO numeric NOT NULL DEFAULT 0,                     -- power play opportunities
    SHG numeric NOT NULL DEFAULT 0,                     -- shorthanded goals
    TEAM numeric NOT NULL DEFAULT 0,                    -- NHL team in-play
    HOME numeric NOT NULL DEFAULT 0,                    -- home or away (0/1)
    DISC numeric NOT NULL DEFAULT 0,                    -- disconnected (0/1)
    QUIT numeric NOT NULL DEFAULT 0,                    -- quit game (0/1)
    CHEAT numeric NOT NULL DEFAULT 0,                   -- cheated (0/1)
    WEIGHT numeric NOT NULL DEFAULT 0,                  -- ?
    SKIL numeric NOT NULL DEFAULT 0,                    -- ?
    TID numeric NOT NULL DEFAULT 0,                     -- ?
    TMID numeric NOT NULL DEFAULT 0,                    -- ?
    VENUE numeric NOT NULL DEFAULT 0,                   -- venue/stadium id
    TYPE numeric NOT NULL DEFAULT 0,                    -- stadium type (NHL, international, ...)
    PNUM numeric NOT NULL DEFAULT 0,                    -- number of periods
    PLEN numeric NOT NULL DEFAULT 0,                    -- period length in minutes
    OT numeric NOT NULL DEFAULT 0,                      -- overtime periods played
    TIME numeric NOT NULL DEFAULT 0,                    -- ingame time
    DTIME numeric NOT NULL DEFAULT 0,                   -- ?
    CONSTRAINT FK_NHL_GAME_REPORT_GAME_CONNECTION_ID FOREIGN KEY (GAME_CONNECTION_ID) REFERENCES core.GAME_CONNECTION(ID)
);

-- NHL Persona Stats table - stores aggregated player statistics
CREATE TABLE IF NOT EXISTS stats.NHL_PERSONA_STATS (
    ID bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    PERSONA_ID bigint NOT NULL,
    VERS varchar(32) NOT NULL,
    SLUS varchar(10) NOT NULL,
    POINTS numeric NOT NULL DEFAULT 0,                  -- total points
    WINS numeric NOT NULL DEFAULT 0,                    -- total wins
    OT_WINS numeric NOT NULL DEFAULT 0,                 -- total overtime wins
    LOSSES numeric NOT NULL DEFAULT 0,                  -- total losses
    OT_LOSSES numeric NOT NULL DEFAULT 0,               -- total overtime losses
    STREAK numeric NOT NULL DEFAULT 0,                  -- current streak (either wins or losses)
    DRAW numeric NOT NULL DEFAULT 0,                    -- total draws
    SCORE numeric NOT NULL DEFAULT 0,                   -- total score (goals scored)
    SCORE_AGAINST numeric NOT NULL DEFAULT 0,           -- total goals conceded
    HITS numeric NOT NULL DEFAULT 0,                    -- total hits
    SHOTS numeric NOT NULL DEFAULT 0,                   -- total shots to net
    PENMIN numeric NOT NULL DEFAULT 0,                  -- total penalty minutes
    PPG numeric NOT NULL DEFAULT 0,                     -- total power play goals
    PPO numeric NOT NULL DEFAULT 0,                     -- total power play opportunities
    SHG numeric NOT NULL DEFAULT 0,                     -- total shorthanded goals
    HOME numeric NOT NULL DEFAULT 0,                    -- total home games played
    AWAY numeric NOT NULL DEFAULT 0,                    -- total away games played
    DISC numeric NOT NULL DEFAULT 0,                    -- total disconnections
    QUIT numeric NOT NULL DEFAULT 0,                    -- total quits
    CHEAT numeric NOT NULL DEFAULT 0,                   -- total cheats
    WEIGHT numeric NOT NULL DEFAULT 0,                  -- total weight
    SKIL numeric NOT NULL DEFAULT 0,                    -- total skill
    TIME numeric NOT NULL DEFAULT 0,                    -- total ingame time
    CONSTRAINT FK_NHL_PERSONA_STATS_PERSONA_ID FOREIGN KEY (PERSONA_ID) REFERENCES core.PERSONA(ID),
    CONSTRAINT UK_NHL_PERSONA_STATS_PERSONA_VERS UNIQUE (PERSONA_ID, VERS)
);
