CREATE TABLE IF NOT EXISTS stats.NFS_GAME_REPORT (
    GAME_CONNECTION_ID BIGINT PRIMARY KEY,
    VENUE numeric,
    GTYP numeric, -- also TYPE in MW
    DIR numeric,
    NUMLAPS numeric, -- also PNUM in MW
    NUMPLYRS numeric,
    CARREST numeric,
    POINTS numeric,
    DISC numeric,
    SKIL numeric,
    TIME numeric, -- total ingame time (until everyone finished), MW sends '1' instead of actual time
    DTIME numeric,
    POS numeric, -- also SCORE MW, 1 = first place, 2 = second place, ... 0 = did not finish
    CAR numeric, -- also CARUSED in MW
    RACETIME numeric, -- total racing time (only time spent driving)
    LAPSCOMP numeric,
    LAP numeric,
    TEAM numeric,
    WEIGHT numeric,
    DSCORE numeric,
    HOME numeric,
    DIDCHEAT numeric, -- also CHEAT in some games
    DIDDISC numeric, -- also DISC in some games (beware, this is different from DISC)
    DIDQUIT numeric, -- also QUIT in some games
    AUTH VARCHAR(64),
    RNK numeric,
    CONSTRAINT FK_NFS_GAME_REPORT_GAME_CONNECTION_ID FOREIGN KEY (GAME_CONNECTION_ID) REFERENCES core.GAME_CONNECTION(ID)
);

CREATE TABLE IF NOT EXISTS stats.NFS_PERSONA_STATS (
    ID bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    PERSONA_ID bigint NOT NULL,
    VERS varchar(32) NOT NULL,
    SLUS varchar(10) NOT NULL,
    WINS numeric NOT NULL DEFAULT 0,
    LOSSES numeric NOT NULL DEFAULT 0,
    SKIL numeric NOT NULL DEFAULT 0,
    TIME numeric NOT NULL DEFAULT 0,
    RACETIME numeric NOT NULL DEFAULT 0,
    LAPSCOMP numeric NOT NULL DEFAULT 0,
    DIDCHEAT numeric NOT NULL DEFAULT 0,
    DIDQUIT numeric NOT NULL DEFAULT 0,
    DIDDISC numeric NOT NULL DEFAULT 0,
    CONSTRAINT FK_NFS_PERSONA_STATS_PERSONA_ID FOREIGN KEY (PERSONA_ID) REFERENCES core.PERSONA(ID),
    CONSTRAINT UK_NFS_PERSONA_STATS_PERSONA_VERS UNIQUE (PERSONA_ID, VERS)
);
